#!/usr/bin/env bash

# Functions
print() {
  local codes=()
  local code_re='^[0-9]+([;][0-9]+)*$'
  while [[ $# -gt 0 && "$1" =~ $code_re ]]; do
    codes+=("$1")
    shift
  done
  local text="${1-}"
  local seq=""
  local code
  for code in "${codes[@]}"; do
    seq+="\033[${code}m"
  done
  if ((${#codes[@]} > 0)); then
    printf '%b%b\033[0m' "$seq" "$text"
  else
    printf '%b' "$text"
  fi
}
# ANSI color codes
RED=31
GREEN=32
YELLOW=33
BLUE=34
MAGENTA=35
CYAN=36
WHITE=37
GRAY=90
BOLD=1
ITALIC=3
UNDERLINE=4
VLC_BASE_ARGS=(--one-instance --fullscreen --sub-language=swe,eng,any --deinterlace=0 --embedded-video --no-loop --no-play-and-pause --no-random --no-repeat --no-video-title-show --qt-auto-raise=0 --qt-continue=0 --qt-fullscreen-screennumber=1 --qt-notification=0 --no-qt-fs-controller --no-qt-name-in-title --no-qt-recentplay --no-qt-updates-notif --no-qt-privacy-ask)

ensure_vlc_running() {
  print "Ensuring VLC is running...\n"
  vlc "${VLC_BASE_ARGS[@]}" --playlist-enqueue --no-playlist-autostart &>/dev/null &
  sleep 1
}
play() {
  local silent=false
  while [[ "$1" == "silent=true" || "$1" == "--silent" ]]; do
    silent=true
    shift
  done
  local file="$1"
  if [[ "$silent" != true ]]; then
    print "Playing $file...\n"
  fi
  vlc "${VLC_BASE_ARGS[@]}" "$file" &>/dev/null
  sleep 1
}
enqueue() {
  local silent=false
  while [[ "$1" == "silent=true" || "$1" == "--silent" ]]; do
    silent=true
    shift
  done
  local file="$1"
  if [[ "$silent" != true ]]; then
    print "Enqueuing $file...\n"
  fi
  vlc "${VLC_BASE_ARGS[@]}" --playlist-enqueue "$file" &>/dev/null
  sleep 1
}
long_pause() {
  local play=false
  while [[ "$1" == "play=true" ]]; do
    play=true
    shift
  done
  print "$GRAY" "Adding long pause block (8 x 30 min)\n"
  if [[ "$play" == true ]]; then
    play silent=true "clips/30_min_pause.mp4"
  else
    enqueue silent=true "clips/30_min_pause.mp4"
  fi
  enqueue silent=true "clips/30_min_pause.mp4"
  enqueue silent=true "clips/30_min_pause.mp4"
  enqueue silent=true "clips/30_min_pause.mp4"
  enqueue silent=true "clips/30_min_pause.mp4"
  enqueue silent=true "clips/30_min_pause.mp4"
  enqueue silent=true "clips/30_min_pause.mp4"
  enqueue silent=true "clips/30_min_pause.mp4"
}
wait_until() {
  local time_string="$1" # e.g. "10:10", "10:10:30", or "10:10.30"
  local target_time
  if [[ "$time_string" =~ ^([0-9]{1,2}):([0-9]{2})([:.]([0-9]{2}))?$ ]]; then
    local hour="${BASH_REMATCH[1]}"
    local minute="${BASH_REMATCH[2]}"
    local second="${BASH_REMATCH[4]:-00}"

    if ((hour > 23 || minute > 59 || second > 59)); then
      print "$YELLOW" "Warning: Invalid time value '$time_string'. Expected HH:MM, HH:MM:SS, or HH:MM.SS. Continuing without waiting.\n"
      return
    fi

    target_time=$(date -d "today $hour:$minute:$second" +%s)
    local now
    while true; do
      now=$(date +%s)
      if ((now >= target_time)); then
        print "$GRAY" "Reached target time $time_string, continuing...\n"
        break
      fi
      sleep 1
    done
  else
    print "$YELLOW" "Warning: Invalid time format '$time_string'. Expected HH:MM, HH:MM:SS, or HH:MM.SS. Continuing without waiting.\n"
  fi
}

print "\n"
print "$BOLD" "This file was generated by Stockholm Trekkers Playlist Maker, made by Vena.\n"
print "$GRAY" "# Author: Vena Ström\n"
print "$GRAY" "# Playlist maker version: 4.0.0\n"
print "$GRAY" "# Repository: https://...\n"
print "$GRAY" "# Contact: strom.vena+stplay@gmail.com\n"
print "$GRAY" "# Options revision: 0\n"
print "$GRAY" "# Playlist date: 2026-05-02\n"
print "$GRAY" "# Created date: 2026-04-19T00:00:00.000Z\n"
print "$GRAY" "# Export date: 2026-04-20T00:00:00.000Z\n"
print "$GRAY" "# Playlist ID: ba1d8d9892da28ef\n"
print "$GRAY" "# Block count: 4\n"
print "$GRAY" "# Episode count: 9\n"

print "$BOLD" "$YELLOW" '\n!!NOTICE!!\n'
print "- Copy playlist folder to the computer.\n"
print "- Check the computers time and timezone settings.\n"
print "- Keep this computer disconnected from the internet for security.\n"
print "\n"

print "Waiting 3 seconds...\n"
sleep 3

print "Embedded description:\n"
# __DESCRIPTION_CODE__
# print "$ITALIC" "$GRAY" "Program för trekdagen 2 maj 2026:\nTEMA:   Vänner och fiender (eller var det kanske tvärt om…)\n\n10:10   The Enemy             TNG 3:7\n10:55   PAUS\n11:25   Blood of Patriots     ORV 2:10\n12:15   Nemesis               VOY 4:4\n13:00   LUNCH\n14:30   Preemptive Strike     TNG 7:24\n15:15   PAUS med uppstart av spel \n15:30   The Shipment          ENT 3:7\n16:15   PAUS\n16:45   For the Cause         DS9 4:21\n17:30   Investigations        VOY 2:20\n18:15   PAUS\n18:30   Hippocratic Oath      DS9 4:3\n19:15   Common Ground         SGA 3:7\n20:00   SLUT"
print "\n\n"

# Constructed "schedule" from the playlist data
print "Parsed playlist\n"
# __PARSED_PLAYLIST_CODE__
# print "$GRAY" "Playlist 2026-05-02\n"
# print "$GRAY" " 9 episodes in 4 blocks\n\n"
# print "$GRAY" " Blocks:\n"
# print "$GRAY" "  - Block 1: 10:10\n"
# print "$GRAY" "     10:10   the-enemy.mkv\n"
# print "$GRAY" "\n"
# print "$GRAY" "  - Block 2: 05:60\n"
# print "$GRAY" "     11:25   Blood-of-Patriots\n"
# print "$GRAY" "     12:15   Nemesis\n"
# print "$GRAY" "\n"
# print "$GRAY" "  - Block 3: 14:00\n"
# print "$GRAY" "     14:30   Preemptive-Strike\n"
# print "$GRAY" "     15:30   The-Shipment\n"
# print "$GRAY" "\n"
# print "$GRAY" "  - Block 4: unknown time\n"
# print "$GRAY" "     16:45   For-the-Cause\n"
print "\n\n"

# Ensure VLC is installed, and is running, ready for control commands
ensure_vlc_running

# Playback logic
print "Starting playback...\n\n"
print "Leading pause block to have something to display\n"
long_pause play=true
print "\n"

# __BLOCKS_CODE__

print "$BOLD" "Playlist ended. No more blocks to play.\n"
print "You may now exit VLC and this script.\n\n"
print "Have a nice evening! :3\n"
print "/ __SIGN_OFF_NAME__ \x1b[31m<3\x1b[0m\n"

# __DELETE__
# Everything after the above line will be deleted by the play-file.ts script so templates can be kept down here.

exit 0 # Fallback in case this gets included

# __BLOCK_TEMPLATE_START__
# Block __BLOCK_NUMBER__
# Block header
wait_until "__ADJUSTED_BLOCK_START_TIME__" # Adjusted for leading clips to align episode start time to block start time
print "$BOLD" "Block __BLOCK_NUMBER__ - __BLOCK_START_TIME__\n"
print "$GRAY" "id=__BLOCK_ID__ options: __BLOCK_OPTIONS__\n"
# Block leading options
# __LEADING_CLIPS_CODE__
# play "episodes/episode"
# Block episodes
print "Block episodes:\n"
# __EPISODES_CODE__
# Block trailing options
# __TRAILING_CLIPS_CODE__
long_pause
print "\n"
# __BLOCK_TEMPLATE_END__
