#!/usr/bin/env bash

# Functions
print() {
  local codes=()
  local code_re='^[0-9]+([;][0-9]+)*$'
  while [[ $# -gt 0 && "$1" =~ $code_re ]]; do
    codes+=("$1")
    shift
  done
  local text="${1-}"
  local seq=""
  local code
  for code in "${codes[@]}"; do
    seq+="\033[${code}m"
  done
  if ((${#codes[@]} > 0)); then
    printf '%b%b\033[0m' "$seq" "$text"
  else
    printf '%b' "$text"
  fi
}
# ANSI color codes
RED=31
GREEN=32
YELLOW=33
BLUE=34
MAGENTA=35
CYAN=36
WHITE=37
GRAY=90
BOLD=1
ITALIC=3
UNDERLINE=4
VLC_BASE_ARGS=(--one-instance --fullscreen --sub-language=swe,eng,any --deinterlace=0 --embedded-video --no-loop --no-play-and-pause --no-random --no-repeat --no-video-title-show --qt-auto-raise=0 --qt-continue=0 --qt-fullscreen-screennumber=1 --qt-notification=0 --no-qt-fs-controller --no-qt-name-in-title --no-qt-recentplay --no-qt-privacy-ask)
VLC_LOG_FILE="./vlc.log"

log_vlc_line() {
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$1" >>"$VLC_LOG_FILE"
}

run_vlc() {
  log_vlc_line "CMD: vlc $*"
  vlc "$@" 2>&1 | while IFS= read -r line; do
    log_vlc_line "$line"
  done
  local exit_code="${PIPESTATUS[0]}"
  log_vlc_line "EXIT: $exit_code"
  return "$exit_code"
}

ensure_vlc_installed() {
  if ! command -v vlc >/dev/null 2>&1; then
    print "$BOLD" "$RED" "VLC was not found on this computer.\n"
    print "Install VLC from https://www.videolan.org/ and run this script again.\n"
    exit 1
  fi
}
kill_existing_vlc() {
  if pgrep -x vlc >/dev/null 2>&1; then
    print "$BOLD" "$YELLOW" "WARNING: VLC is already running. Closing it so the playlist starts from a clean slate...\n"
    pkill -x vlc
    sleep 2
  fi
}
ensure_vlc_running() {
  run_vlc "${VLC_BASE_ARGS[@]}" --playlist-enqueue --no-playlist-autostart &
  sleep 1
}
play() {
  local silent=false
  while [[ "$1" == "silent=true" || "$1" == "--silent" ]]; do
    silent=true
    shift
  done
  local file="$1"
  if [[ "$silent" != true ]]; then
    print "$GREEN" "> Now playing: "
    print "$file\n"
  fi
  run_vlc "${VLC_BASE_ARGS[@]}" "$file"
  sleep 1
}
enqueue() {
  local silent=false
  while [[ "$1" == "silent=true" || "$1" == "--silent" ]]; do
    silent=true
    shift
  done
  local file="$1"
  if [[ "$silent" != true ]]; then
    print "$GRAY" "  + Queued: $file\n"
  fi
  run_vlc "${VLC_BASE_ARGS[@]}" --playlist-enqueue "$file"
  sleep 1
}
long_pause() {
  local play=false
  while [[ "$1" == "play=true" ]]; do
    play=true
    shift
  done
  print "$GRAY" "Queueing pause filler (8 x 30 min = 4 h)\n"
  if [[ "$play" == true ]]; then
    play silent=true "clips/30_min_pause.mp4"
  else
    enqueue silent=true "clips/30_min_pause.mp4"
  fi
  enqueue silent=true "clips/30_min_pause.mp4"
  enqueue silent=true "clips/30_min_pause.mp4"
  enqueue silent=true "clips/30_min_pause.mp4"
  enqueue silent=true "clips/30_min_pause.mp4"
  enqueue silent=true "clips/30_min_pause.mp4"
  enqueue silent=true "clips/30_min_pause.mp4"
  enqueue silent=true "clips/30_min_pause.mp4"
}
wait_until() {
  local time_string="$1" # e.g. "10:10", "10:10:30", or "10:10.30"
  local label="${2:-Playback}"
  local target_time
  if [[ "$time_string" =~ ^([0-9]{1,2}):([0-9]{2})([:.]([0-9]{2}))?$ ]]; then
    local hour="${BASH_REMATCH[1]}"
    local minute="${BASH_REMATCH[2]}"
    local second="${BASH_REMATCH[4]:-00}"
    local hour_num=$((10#$hour))
    local minute_num=$((10#$minute))
    local second_num=$((10#$second))

    if ((hour_num > 23 || minute_num > 59 || second_num > 59)); then
      print "$BOLD" "$YELLOW" "WARNING: Invalid time value '$time_string'. Expected HH:MM, HH:MM:SS, or HH:MM.SS. Continuing without waiting.\n"
      return
    fi

    target_time=$(date -d "today $hour_num:$minute_num:$second_num" +%s)
    local now remaining
    now=$(date +%s)
    if ((now >= target_time)); then
      print "$BOLD" "$YELLOW" "WARNING: $label was scheduled for $time_string, which has already passed. Continuing immediately.\n"
      return
    fi
    while true; do
      now=$(date +%s)
      if ((now >= target_time)); then
        break
      fi
      remaining=$((target_time - now))
      # Live countdown, redrawn in place on one line
      printf '\r\033[K'
      print "$CYAN" "$label starts at $time_string"
      print "$GRAY" " - in $(printf '%02d:%02d:%02d' $((remaining / 3600)) $((remaining % 3600 / 60)) $((remaining % 60))) (clock: $(date '+%H:%M:%S'))"
      sleep 1
    done
    printf '\r\033[K'
    print "$GREEN" "Reached $time_string - starting $label.\n"
  else
    print "$BOLD" "$YELLOW" "WARNING: Invalid time format '$time_string'. Expected HH:MM, HH:MM:SS, or HH:MM.SS. Continuing without waiting.\n"
  fi
}

print "\n"
print "$BOLD" "This file was generated by Stockholm Trekkers Playlist Maker, made by __SIGN_OFF_NAME__.\n"
print "$GRAY" "# Author: __AUTHOR__\n"
print "$GRAY" "# Playlist maker version: __APP_VERSION__\n"
print "$GRAY" "# Repository: __REPO_URL__\n"
print "$GRAY" "# Contact: __EMAIL__\n"
print "$GRAY" "# Options revision: __OPTIONS_REV__\n"
print "$GRAY" "# Playlist date: __PLAYLIST_DATE__\n"
print "$GRAY" "# Created date: __CREATED_DATE__\n"
print "$GRAY" "# Export date: __EXPORTED_DATE__\n"
print "$GRAY" "# Playlist ID: __PLAYLIST_ID__\n"
print "$GRAY" "# Block count: __BLOCK_COUNT__\n"
print "$GRAY" "# Episode count: __EPISODE_COUNT__\n"

print "$BOLD" "$YELLOW" '\n!!NOTICE!!\n'
print "- Copy playlist folder to the computer.\n"
print "- Check the computers time and timezone settings.\n"
print "- Keep this computer disconnected from the internet for security.\n"
print "\n"
print "$GRAY" "VLC logs will be written to $VLC_LOG_FILE\n"

print "Waiting 3 seconds...\n"
sleep 3

# Ensure VLC is installed, close stray instances, then start ours ready for control commands
ensure_vlc_installed
kill_existing_vlc
ensure_vlc_running

print "Embedded description:\n"
__DESCRIPTION_CODE__
print "\n\n"

# Constructed "schedule" from the playlist data
print "Parsed playlist\n"
__PARSED_PLAYLIST_CODE__
print "\n\n"

# Playback logic
print "Starting playback...\n\n"
print "Leading pause block to have something to display\n"
long_pause play=true
print "\n"

__BLOCKS_CODE__

print "$BOLD" "Playlist ended. No more blocks to play.\n"
print "You may now exit VLC and this script.\n\n"
print "Have a nice evening! :3\n"
print "/ __SIGN_OFF_NAME__ \x1b[31m<3\x1b[0m\n"
