import { spawnSync } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import ffmpegStatic from "ffmpeg-static";

function extractOptions(helpOutput: string): string[] {
  const options = new Set<string>();
  const lines = helpOutput.split(/\r?\n/u);

  for (const line of lines) {
    const match = line.match(/^\s*(-{1,2}[^\s,=\]]+)/u);

    if (!match) {
      continue;
    }

    const token = match[1]?.trim();

    if (!token || token === "-" || token === "--") {
      continue;
    }

    options.add(token);
  }

  return Array.from(options).sort((a, b) => a.localeCompare(b));
}

function renderGeneratedTypes(options: string[]): string {
  const escapedOptions = options.map((option) => JSON.stringify(option));

  return [
    "// This file is auto-generated by scripts/generate-ffmpeg-arg-types.ts.",
    "// Re-run `yarn generate-ffmpeg-arg-types` when FFmpeg changes.",
    "",
    "export const KNOWN_FFMPEG_OPTIONS = [",
    ...escapedOptions.map((option) => `  ${option},`),
    "] as const;",
    "",
    "export type KnownFFmpegOption = (typeof KNOWN_FFMPEG_OPTIONS)[number];",
    "",
    "// Keep a wide string fallback for dynamic args that are not known at generation time.",
    "export type FFmpegArg = KnownFFmpegOption | (string & {});",
    "",
    "const KNOWN_FFMPEG_OPTION_SET = new Set<string>(KNOWN_FFMPEG_OPTIONS);",
    "",
    "export function isKnownFFmpegOption(value: string): value is KnownFFmpegOption {",
    "  return KNOWN_FFMPEG_OPTION_SET.has(value);",
    "}",
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  if (!ffmpegStatic) {
    throw new Error("ffmpeg-static did not resolve a binary path.");
  }

  const command = spawnSync(ffmpegStatic, ["-hide_banner", "-h", "full"], {
    encoding: "utf8",
    maxBuffer: 1024 * 1024 * 16,
  });

  if (command.error) {
    throw command.error;
  }

  if (command.status !== 0 && !command.stdout && !command.stderr) {
    throw new Error(`Unable to inspect ffmpeg options. Exit code: ${String(command.status)}`);
  }

  const rawHelp = `${command.stdout}\n${command.stderr}`;
  const options = extractOptions(rawHelp);

  if (options.length === 0) {
    throw new Error("No ffmpeg options were detected from help output.");
  }

  const outputPath = resolve("src", "types", "ffmpeg-args.generated.ts");
  await writeFile(outputPath, renderGeneratedTypes(options), "utf8");

  console.info(`Generated ${options.length} ffmpeg options at ${outputPath}`);
}

await main();
